// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqY7TsFhEgyxKwbtxqmerCqtX2IKrktc',
    appId: '1:529859684260:web:824114e99d0ecb82168331',
    messagingSenderId: '529859684260',
    projectId: 'intune-quattonary',
    authDomain: 'intune-quattonary.firebaseapp.com',
    storageBucket: 'intune-quattonary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kdjToYV6yPwt6CVfL5yr1pR_6P_amAY',
    appId: '1:529859684260:android:01c95b000ca05dd0168331',
    messagingSenderId: '529859684260',
    projectId: 'intune-quattonary',
    storageBucket: 'intune-quattonary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8yJGfFGQPZKGv8TnnTzJkrSnlU_UNlc',
    appId: '1:529859684260:ios:32609bf757d91071168331',
    messagingSenderId: '529859684260',
    projectId: 'intune-quattonary',
    storageBucket: 'intune-quattonary.appspot.com',
    iosClientId: '529859684260-heqau763rurt27k7j7qt7p8j3frqhrn2.apps.googleusercontent.com',
    iosBundleId: 'com.quattonary.intune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8yJGfFGQPZKGv8TnnTzJkrSnlU_UNlc',
    appId: '1:529859684260:ios:32609bf757d91071168331',
    messagingSenderId: '529859684260',
    projectId: 'intune-quattonary',
    storageBucket: 'intune-quattonary.appspot.com',
    iosClientId: '529859684260-heqau763rurt27k7j7qt7p8j3frqhrn2.apps.googleusercontent.com',
    iosBundleId: 'com.quattonary.intune',
  );
}
